package pl.parser.nbp.exchangeRate;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The {@code ExchangeRate} class represents the currency exchange
 * rate for buy and sale downloaded from NBP XML files. It includes
 * allArgsConstructor, noArgsConstructor, getter, setter, toString,
 * equals and hashCode methods generated by Lombok library.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
class ExchangeRate {

    private String currencyCode;
    private Float currencyBuyRate;
    private Float currencySellRate;
}
