package pl.parser.nbp.inputArgs;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * The {@code InputArgs} class represents arguments entered by user
 * and includes allArgsConstructor, noArgsConstructor, getter, setter,
 * toString, equals and hashCode methods generated by Lombok library.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class InputArgs {

    private String currencyCode;
    private LocalDate startDate;
    private LocalDate endDate;
}
